const path = require('path')
const express = require('express')
const museumController = require('../controllers/museum')
const router = express.Router()
// query 1
// router.get('/query', museumController.query)
router.get('/object1', museumController.object1)
router.get('/object2', museumController.object2)
router.get('/object3', museumController.object3)
router.get('/object4', museumController.object4)
router.get('/object5', museumController.object5)
router.get('/criar-colecao', museumController.getColecao)
router.post('/criar-colecao', museumController.postColecao)
router.get('/criar-objeto', museumController.getObjeto)
router.post('/criar-objeto', museumController.postObjeto)
router.get('/criar-permanente', museumController.getPermanente)
router.post('/criar-permanente', museumController.postPermanente)
router.get('/criar-emprestado', museumController.getEmprestado)
router.post('/criar-emprestado', museumController.postEmprestado)
module.exports = router